import { LockKeyhole } from "lucide-react";
import { getLevelDisplayName } from "../../data/fallbackCourses";
import type { Course, NativeLanguageCode } from "../../types/index";
import { useTranslation } from "../../i18n/useTranslation";
import { Badge } from "../ui/Badge";
import { UnitSection } from "./UnitSection";

export function CoursePath({ course, completedIds, unlockedIds, placedIds, currentLessonId, nativeLanguage }: { course: Course; completedIds: string[]; unlockedIds: string[]; placedIds: string[]; currentLessonId: string | null; nativeLanguage?: NativeLanguageCode }) {
  const { t, language } = useTranslation();
  return <div className="space-y-8">{course.examTracks?.length ? <section className="rounded-2xl border border-white/[.06] bg-white/[.03] p-4"><p className="text-xs font-black uppercase tracking-[.16em] text-cyan-300">{t("examPreparation")}</p><div className="mt-3 grid gap-2 sm:grid-cols-2">{course.examTracks.map((track) => <div key={track.id} className={`rounded-xl border p-3 ${track.comingSoon ? "border-white/5 bg-white/[.025] text-slate-500" : "border-cyan-300/20 bg-cyan-300/10 text-cyan-100"}`}><div className="flex items-center justify-between gap-3"><strong className="text-sm">{track.levelId ? getLevelDisplayName(track.levelId, course.language, nativeLanguage) : track.title}</strong>{track.comingSoon && <span className="rounded-lg bg-white/[.06] px-2 py-1 text-[10px] font-black uppercase tracking-wider">{t("comingSoon")}</span>}</div><p className="mt-1 text-xs leading-5 text-slate-500">{language === "vi" ? (track.comingSoon ? t("moreRoadmap") : t("signalDescription")) : track.description}</p></div>)}</div></section> : null}{course.levels.map((level) => { const levelName = getLevelDisplayName(level.id, course.language, nativeLanguage); const title = course.language === "ja" ? levelName : level.title; return <section key={level.id} className="rounded-3xl border border-white/[.06] bg-black/10 p-4 sm:p-6"><div className="mb-7 flex items-start justify-between gap-4"><div><Badge tone={level.id === "A0" ? "cyan" : level.comingSoon ? "slate" : "pink"}>{t("level")} {levelName}</Badge><h2 className="mt-3 font-display text-2xl font-black">{title}{level.comingSoon ? ` ${t("comingSoon")}` : ""}</h2><p className="mt-1 text-sm leading-6 text-slate-500">{language === "vi" ? t("signalDescription") : level.description}</p></div><span className="rounded-xl bg-white/5 px-3 py-2 text-xs font-black text-slate-400">{level.comingSoon ? t("comingSoon") : levelName}</span></div>{level.comingSoon || !level.units.length ? <div className="rounded-2xl border border-dashed border-white/10 bg-white/[.025] p-5 text-sm font-bold text-slate-500"><LockKeyhole className="mr-2 inline" size={15} />{t("moreRoadmap")}</div> : level.units.map((unit) => <UnitSection key={unit.id} unit={unit} completedIds={completedIds} unlockedIds={unlockedIds} placedIds={placedIds} currentLessonId={currentLessonId} />)}</section>; })}</div>;
}
