import { BookOpen, CreditCard, Flame, Heart, Languages as LanguagesIcon, LogOut, RotateCcw, Settings, Sparkles, Trophy, Zap } from "lucide-react";
import { useState } from "react";
import { Link } from "react-router-dom";
import { AchievementBadge, achievementCatalog } from "../components/learning/AchievementBadge";
import { Mascot } from "../components/learning/Mascot";
import { StatCard } from "../components/learning/StatCard";
import { PageContainer } from "../components/layout/PageContainer";
import { NativeLanguageSelector } from "../components/NativeLanguageSelector";
import { Badge } from "../components/ui/Badge";
import { Button } from "../components/ui/Button";
import { Card } from "../components/ui/Card";
import { Modal } from "../components/ui/Modal";
import { useApp } from "../context/AppContext";
import { useAuth } from "../context/AuthContext";
import { getLevelDisplayName, languages } from "../data/fallbackCourses";
import { useTranslation } from "../i18n/useTranslation";
import type { LanguageCode } from "../types/index";
import { getNativeLanguageInfo } from "../utils/storage";

export function ProfilePage() {
  const { progress, resetProgress, selectLanguage } = useApp(); const { user, signOut } = useAuth(); const { t } = useTranslation();
  const [confirmReset, setConfirmReset] = useState(false); const [pendingLanguage, setPendingLanguage] = useState<LanguageCode>();
  const language = languages.find((item) => item.code === progress.selectedLanguage) ?? languages[0];
  const nativeLanguage = getNativeLanguageInfo(progress.nativeLanguage); const currentLevelName = getLevelDisplayName(progress.currentLevel, progress.learningLanguage, progress.nativeLanguage);
  const languageName = (code: LanguageCode) => code === "en" ? t("english") : code === "ja" ? t("japanese") : t("spanish");
  return <PageContainer className="py-8 sm:py-11"><section className="relative overflow-hidden rounded-[2rem] border border-white/10 bg-gradient-to-br from-violet-400/15 via-fuchsia-400/[.08] to-cyan-300/[.08] p-6 sm:p-9"><div className="relative flex flex-col gap-6 sm:flex-row sm:items-center"><Mascot size="md" /><div className="flex-1"><Badge tone="cyan">{t("profileTitle")}</Badge><h1 className="mt-3 font-display text-3xl font-black">{user?.name}</h1><p className="mt-1 text-sm text-slate-500">{user?.email}</p><p className="mt-4 text-sm font-extrabold text-cyan-200">{language.flag} {languageName(language.code)} · {currentLevelName} · {progress.dailyGoalMinutes} {t("minutesDay")}</p></div><Button variant="ghost" onClick={signOut}><LogOut size={17} />{t("signOut")}</Button></div></section><section className="mt-5 grid grid-cols-2 gap-3 lg:grid-cols-4"><StatCard icon={Zap} label={t("totalXp")} value={progress.totalXp} color="text-violet-300" /><StatCard icon={Flame} label={t("streak")} value={progress.streak} color="text-orange-300" /><StatCard icon={BookOpen} label={t("lessonsComplete")} value={progress.completedLessonIds.length} color="text-cyan-300" /><StatCard icon={CreditCard} label={t("flashcards")} value={progress.savedFlashcards.length} color="text-fuchsia-300" /></section>
  <Card className="mt-7 p-6 sm:p-8"><div className="flex items-center gap-3"><Settings className="text-cyan-300" /><div><p className="text-xs font-black uppercase tracking-wider text-cyan-300">{t("settings")}</p><h2 className="font-display text-2xl font-black">{t("languageSettings")}</h2></div></div><div className="mt-6 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border border-white/10 bg-white/[.035] p-4"><p className="text-[10px] font-black uppercase tracking-wider text-cyan-300">{t("nativeLanguage")}</p><strong className="mt-2 block text-sm">{nativeLanguage.nativeName}</strong><span className="text-xs text-slate-500">{nativeLanguage.name}</span></div><div className="rounded-2xl border border-white/10 bg-white/[.035] p-4"><p className="text-[10px] font-black uppercase tracking-wider text-violet-300">{t("uiLanguage")}</p><strong className="mt-2 block text-sm">{progress.effectiveUILanguage === "en" ? t("english") : progress.effectiveUILanguage === "vi" ? t("vietnamese") : progress.effectiveUILanguage === "ja" ? t("japanese") : t("spanish")}</strong><span className="text-xs text-slate-500">{progress.effectiveUILanguage.toUpperCase()}</span></div><div className="rounded-2xl border border-white/10 bg-white/[.035] p-4"><p className="text-[10px] font-black uppercase tracking-wider text-fuchsia-300">{t("learningLanguage")}</p><strong className="mt-2 block text-sm">{languageName(progress.learningLanguage)}</strong><span className="text-xs text-slate-500">{progress.learningLanguage.toUpperCase()}</span></div></div><div className="mt-7"><h3 className="font-display text-lg font-black">{t("changeNativeLanguage")}</h3><p className="mt-1 text-sm text-slate-500">{t("changeNativeHelp")}</p><div className="mt-4"><NativeLanguageSelector compact /></div></div><div className="mt-8 border-t border-white/10 pt-7"><h3 className="font-display text-lg font-black">{t("learningLanguage")}</h3><p className="mt-1 text-sm text-slate-500">{t("changeLearningWarning")}</p><div className="mt-4 grid gap-3 sm:grid-cols-3">{languages.map((item) => <button key={item.code} onClick={() => item.code !== progress.selectedLanguage && setPendingLanguage(item.code)} className={`rounded-2xl border p-4 text-left transition ${item.code === progress.selectedLanguage ? "border-violet-300/45 bg-violet-300/10" : "border-white/10 bg-white/[.035] hover:border-cyan-300/30"}`}><span className="text-2xl">{item.flag}</span><strong className="ml-3">{languageName(item.code)}</strong></button>)}</div>{progress.placementResult && <Link to={`/placement/${progress.selectedLanguage}`}><Button variant="secondary" className="mt-4"><RotateCcw size={16} />{t("retakePlacement")}</Button></Link>}</div></Card>
  <section className="mt-7"><div className="mb-5 flex items-center gap-3"><Trophy className="text-amber-300" /><div><p className="text-xs font-black uppercase tracking-wider text-amber-300">{t("achievementGrid")}</p><h2 className="font-display text-2xl font-black">{t("completed")}</h2></div></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{achievementCatalog.map((achievement) => <AchievementBadge key={achievement.id} title={achievement.title} description={achievement.description} earned={progress.achievements.includes(achievement.id)} />)}</div></section>
  <Card className="mt-7 flex flex-col items-start justify-between gap-5 p-6 sm:flex-row sm:items-center"><div><div className="flex items-center gap-2"><Heart className="text-rose-300" fill="currentColor" /><h2 className="font-display text-xl font-black">{t("resetProgress")}</h2></div><p className="mt-2 text-sm leading-6 text-slate-500">{t("resetBody")}</p></div><Button variant="danger" onClick={() => setConfirmReset(true)}><RotateCcw size={17} />{t("resetProgress")}</Button></Card>
  <Modal open={!!pendingLanguage} title={t("learningLanguage")} onClose={() => setPendingLanguage(undefined)}><LanguagesIcon className="text-cyan-300" /><p className="mt-4 text-sm leading-6 text-slate-400">{t("changeLearningWarning")}</p><div className="mt-6 flex gap-3"><Button variant="ghost" className="flex-1" onClick={() => setPendingLanguage(undefined)}>{t("cancel")}</Button><Button className="flex-1" onClick={() => { if (pendingLanguage) selectLanguage(pendingLanguage); setPendingLanguage(undefined); }}>{t("continue")}</Button></div></Modal>
  <Modal open={confirmReset} title={t("resetTitle")} onClose={() => setConfirmReset(false)}><Sparkles className="text-rose-300" /><p className="mt-4 text-sm leading-6 text-slate-400">{t("resetBody")}</p><div className="mt-6 flex gap-3"><Button variant="ghost" className="flex-1" onClick={() => setConfirmReset(false)}>{t("cancel")}</Button><Button variant="danger" className="flex-1" onClick={() => { resetProgress(); setConfirmReset(false); }}>{t("resetEverything")}</Button></div></Modal></PageContainer>;
}

