import 'dart:convert';

import 'package:shared_preferences/shared_preferences.dart';

class ExerciseReviewRecord {
  const ExerciseReviewRecord({
    required this.attemptId,
    required this.userId,
    required this.localStudyDate,
    required this.lessonId,
    required this.lessonTitle,
    required this.exerciseId,
    required this.exerciseNumber,
    required this.exerciseType,
    required this.questionDisplay,
    required this.userAnswer,
    required this.correctAnswer,
    required this.isCorrect,
    required this.completedAt,
    this.subQuestionId,
    this.score,
    this.shortExplanation,
    this.explanationLanguageCode,
    this.correctedExample,
    this.missingParts = const [],
    this.answerMetadata = const {},
  });

  final String attemptId;
  final String userId;
  final String localStudyDate;
  final String lessonId;
  final String lessonTitle;
  final String exerciseId;
  final int exerciseNumber;
  final String? subQuestionId;
  final String exerciseType;
  final String questionDisplay;
  final String userAnswer;
  final String correctAnswer;
  final bool isCorrect;
  final int? score;

  /// Snapshot explanation text captured at answer-check time.
  ///
  /// For statically authored exercises (the vast majority — anything with a
  /// content-defined `feedback.explanation`/`explanationByNative`), this is a
  /// redundant last-resort fallback only: the review UI re-resolves the
  /// explanation live from the lesson content using [lessonId]/[exerciseId]/
  /// [subQuestionId] and the *current* `nativeLanguageCode`, so it never goes
  /// stale when the learner switches native language. It is only actually
  /// relied upon when [explanationLanguageCode] is set (AI-graded exercises,
  /// whose explanation text is generated once per answer and cannot be
  /// re-resolved without another AI call).
  final String? shortExplanation;

  /// The `nativeLanguageCode` active when [shortExplanation] was generated by
  /// an AI grader. Null for statically authored explanations (which are
  /// re-resolved live and therefore never go stale) and for legacy records
  /// persisted before this field existed. A non-null value lets the review
  /// UI detect a locale mismatch instead of silently showing frozen-language
  /// AI text as if it matched the learner's current native language.
  final String? explanationLanguageCode;
  final String? correctedExample;
  final List<int> missingParts;
  final Map<String, String> answerMetadata;
  final String completedAt;

  /// Exercise types whose wrong-answer explanation is generated dynamically
  /// per answer by an AI grader, rather than authored statically in content.
  /// Only these types rely on [explanationLanguageCode]; every other type is
  /// re-resolved live from content at the learner's current native language.
  static const Set<String> aiGradedExerciseTypes = {
    'controlled_ai_text',
    'controlledAiQa',
    'aiFeedbackReview',
  };

  bool get isAiGradedExplanation => aiGradedExerciseTypes.contains(exerciseType);

  String get dedupeKey => [
    userId,
    localStudyDate,
    attemptId,
    lessonId,
    exerciseId,
    subQuestionId ?? '',
  ].join('|');

  Map<String, dynamic> toJson() => {
    'attemptId': attemptId,
    'userId': userId,
    'localStudyDate': localStudyDate,
    'lessonId': lessonId,
    'lessonTitle': lessonTitle,
    'exerciseId': exerciseId,
    'exerciseNumber': exerciseNumber,
    'subQuestionId': subQuestionId,
    'exerciseType': exerciseType,
    'questionDisplay': questionDisplay,
    'userAnswer': userAnswer,
    'correctAnswer': correctAnswer,
    'isCorrect': isCorrect,
    'score': score,
    'shortExplanation': shortExplanation,
    'explanationLanguageCode': explanationLanguageCode,
    'correctedExample': correctedExample,
    'missingParts': missingParts,
    'answerMetadata': answerMetadata,
    'completedAt': completedAt,
  };

  factory ExerciseReviewRecord.fromJson(Map<String, dynamic> json) =>
      ExerciseReviewRecord(
        attemptId: '${json['attemptId'] ?? ''}',
        userId: '${json['userId'] ?? ''}',
        localStudyDate: '${json['localStudyDate'] ?? ''}',
        lessonId: '${json['lessonId'] ?? ''}',
        lessonTitle: '${json['lessonTitle'] ?? ''}',
        exerciseId: '${json['exerciseId'] ?? ''}',
        exerciseNumber: json['exerciseNumber'] as int? ?? 0,
        subQuestionId: json['subQuestionId']?.toString(),
        exerciseType: '${json['exerciseType'] ?? ''}',
        questionDisplay: '${json['questionDisplay'] ?? ''}',
        userAnswer: '${json['userAnswer'] ?? ''}',
        correctAnswer: '${json['correctAnswer'] ?? ''}',
        isCorrect: json['isCorrect'] == true,
        score: json['score'] as int?,
        shortExplanation: json['shortExplanation']?.toString(),
        // Absent on every record persisted before this fix — treated as
        // "unknown locale" by the review UI, never as a silent locale match.
        explanationLanguageCode: json['explanationLanguageCode']?.toString(),
        correctedExample: json['correctedExample']?.toString(),
        missingParts: (json['missingParts'] as List? ?? const [])
            .whereType<int>()
            .toList(),
        answerMetadata: (json['answerMetadata'] as Map? ?? const {}).map(
          (key, value) => MapEntry('$key', '$value'),
        ),
        completedAt: '${json['completedAt'] ?? ''}',
      );
}

abstract interface class WrongAnswerRepository {
  Future<void> upsert(ExerciseReviewRecord record);
  Future<void> resolve(ExerciseReviewRecord record);
  Future<List<ExerciseReviewRecord>> forLesson({
    required String userId,
    required String lessonId,
  });
}

/// Trial-only local store. Its interface is intentionally account/date scoped
/// so a production implementation can later synchronize the same records.
class SharedPreferencesExerciseReviewRepository
    implements WrongAnswerRepository {
  static const _key = 'novalang_exercise_review_v1';

  Future<List<ExerciseReviewRecord>> _read() async {
    final value = (await SharedPreferences.getInstance()).getString(_key);
    if (value == null) return [];
    try {
      return (jsonDecode(value) as List)
          .whereType<Map>()
          .map(
            (item) =>
                ExerciseReviewRecord.fromJson(Map<String, dynamic>.from(item)),
          )
          .toList();
    } catch (_) {
      return [];
    }
  }

  String _wrongKey(ExerciseReviewRecord record) =>
      '${record.userId}|${record.lessonId}|${record.exerciseId}|${record.subQuestionId ?? ''}';

  @override
  Future<void> upsert(ExerciseReviewRecord record) async {
    final byKey = {for (final item in await _read()) _wrongKey(item): item};
    byKey[_wrongKey(record)] = record;
    await (await SharedPreferences.getInstance()).setString(
      _key,
      jsonEncode(byKey.values.map((item) => item.toJson()).toList()),
    );
  }

  @override
  Future<void> resolve(ExerciseReviewRecord record) async {
    final items = await _read();
    final key = _wrongKey(record);
    items.removeWhere((item) => _wrongKey(item) == key);
    await (await SharedPreferences.getInstance()).setString(
      _key,
      jsonEncode(items.map((item) => item.toJson()).toList()),
    );
  }

  @override
  Future<List<ExerciseReviewRecord>> forLesson({
    required String userId,
    required String lessonId,
  }) async =>
      (await _read())
          .where(
            (item) =>
                item.userId == userId &&
                item.lessonId == lessonId &&
                !item.isCorrect,
          )
          .toList()
        ..sort((a, b) => a.completedAt.compareTo(b.completedAt));
}

class InMemoryExerciseReviewRepository implements WrongAnswerRepository {
  final Map<String, ExerciseReviewRecord> _records = {};

  @override
  Future<void> upsert(ExerciseReviewRecord record) async {
    _records['${record.userId}|${record.lessonId}|${record.exerciseId}|${record.subQuestionId ?? ''}'] =
        record;
  }

  @override
  Future<void> resolve(ExerciseReviewRecord record) async {
    _records.remove(
      '${record.userId}|${record.lessonId}|${record.exerciseId}|${record.subQuestionId ?? ''}',
    );
  }

  @override
  Future<List<ExerciseReviewRecord>> forLesson({
    required String userId,
    required String lessonId,
  }) async => _records.values
      .where((item) => item.userId == userId && item.lessonId == lessonId)
      .toList();
}

String localStudyDate([DateTime? value]) {
  final local = value ?? DateTime.now();
  return '${local.year.toString().padLeft(4, '0')}-${local.month.toString().padLeft(2, '0')}-${local.day.toString().padLeft(2, '0')}';
}
