import type { SupportedUILanguage } from "../types/index";

const en = {
  appName: "NovaLang", tagline: "Master languages through AI-powered quests.", signIn: "Sign in", signOut: "Sign out", startLearning: "Start learning", exploreCourses: "Explore courses",
  chooseNativeLanguage: "Choose your native language", nativeLanguageHelp: "Your native language is separate from the language you study.", chooseLearningLanguage: "Choose the language you want to learn", chooseLevel: "Where are you starting?", chooseGoal: "Set your daily goal", chooseDailyGoal: "Choose your daily goal", searchLanguage: "Search languages", popularLanguages: "Popular languages", allLanguages: "All languages", selectedNativeLanguage: "Selected native language", uiLanguage: "Interface language", changeNativeLanguage: "Change native language", unsupportedUINotice: "English interface fallback", englishFallbackNotice: "Your native language has been saved. Full interface translation is not available yet, so NovaLang will use English for the interface.", save: "Save", placementTest: "Placement test", startFromZero: "Start from zero",
  english: "English", vietnamese: "Vietnamese", japanese: "Japanese", spanish: "Spanish", beginner: "Beginner", elementary: "Elementary", intermediate: "Intermediate", casual: "Casual", regular: "Regular", serious: "Serious", minutesDay: "min/day",
  back: "Back", backToCourse: "Back to course", reviewLesson: "Review lesson", previousMicro: "Review previous step", nextMicroNav: "Next", continue: "Continue", launchPath: "Launch my path", welcomeBack: "Welcome back", continueStreak: "Continue your streak", email: "Email", password: "Password", forgotPassword: "Forgot password?", enterApp: "Enter NovaLang", createProfile: "Create a profile", continueExplorer: "Continue as an explorer",
  home: "Home", learn: "Learn", practice: "Practice", review: "Review", mistakes: "Mistakes", flashcards: "Flashcards", profile: "Profile", settings: "Settings",
  totalXp: "Total XP", streak: "Day streak", hearts: "Hearts", lessonsComplete: "Lessons complete", dailyGoal: "Daily goal", xpToday: "XP earned today", coursePath: "Course path", currentLevel: "Current level", level: "Level", unit: "Unit", placed: "Placed", completed: "Completed", locked: "Locked", current: "Current",
  signalLive: "Your {language} signal is live.", signalDescription: "Complete the glowing lesson and each micro-step will unlock the next.", reviewChamber: "Review chamber", practiceDescription: "Practice learned signals for XP and recover one heart.", mistakeSignals: "Mistake signals", reviewMistakes: "Review mistakes",
  lessonIntro: "Lesson intro", canDo: "Can-do goal", microLessons: "Micro-lessons", microProgress: "Micro-lesson progress", beginMicro: "Begin micro-lesson", continueMicro: "Continue micro-lesson", nextMicro: "Next micro-lesson", microComplete: "Micro-lesson complete", lessonComplete: "Main lesson complete", questComplete: "Quest complete", xpEarned: "XP earned", accuracy: "Accuracy", correct: "Correct", heartsLeft: "Hearts left", newQuestUnlocked: "New quest unlocked", coursePathButton: "Course path",
  readingLabel: "Reading", exampleWordLabel: "Example word", meaningLabel: "Meaning", exampleLabel: "Example", translationLabel: "Translation", vocabulary: "Vocabulary", pronunciation: "Pronunciation", grammar: "Grammar", dialogue: "Dialogue", saveFlashcard: "Save flashcard", saved: "Saved", explanation: "Explanation", exercises: "Exercises", startExercises: "Start exercises · {count}", exerciseNumber: "Exercise {current}/{total}", checkAnswer: "Check answer", nextExercise: "Next exercise", finishMicro: "Finish micro-lesson", correctSignal: "Correct signal", notQuite: "Not quite yet", practiceRecover: "Practice to recover hearts",
  lockedLessonTitle: "This lesson is still locked", lockedLessonText: "Complete the previous lesson and its micro-lessons first.", lockedMicroTitle: "This micro-lesson is locked", lockedMicroText: "Complete the previous micro-lesson to continue.", loading: "Tuning the learning signal…", playPronunciation: "Play pronunciation", speaking: "Playing pronunciation", speechNotSupported: "Speech playback is not supported by this browser.", pronunciationFailed: "Pronunciation is not available in this browser.", voiceUnavailable: "No matching {language} voice is installed. Add this voice in your browser or device speech settings.",
  placementTitle: "Find your best starting point", placementDescription: "Answer mixed questions. Nova will recommend a CEFR or JLPT-style starting level.", startPlacement: "Start placement test", skipPlacement: "Start from zero", placementQuestion: "Placement question", placementResult: "Your recommended level", score: "Score", recommendedUnit: "Recommended unit", recommendedLesson: "Recommended lesson", startRecommended: "Start recommended path", retakePlacement: "Retake placement test",
  dailyReview: "Daily Review", weakWords: "Weak Words", grammarReview: "Grammar Review", pronunciationReview: "Pronunciation Review", mistakeReview: "Mistake Review", dueItems: "items due", knewIt: "I knew it", reviewAgain: "Review again", reviewEmpty: "No review items are due yet.", reviewEmptyHelp: "Complete micro-lessons to build your spaced-review queue.",
  flashcardTitle: "Your saved flashcards", flashcardHelp: "Tap a card to flip it.", flashcardEmpty: "Your word vault is empty", mistakesTitle: "Turn weak signals into strengths.", noMistakes: "No unresolved mistakes", retrySignal: "Retry signal", improved: "Improved!",
  profileTitle: "Explorer profile", achievementGrid: "Achievement grid", languageSettings: "Language Settings", nativeLanguage: "Native language", learningLanguage: "Learning language", changeNativeHelp: "Changing the interface language keeps all learning progress.", changeLearningWarning: "Changing the learning language changes the visible course, but preserves every course’s progress.", resetProgress: "Reset progress", resetTitle: "Reset your learning signal?", resetBody: "This removes learning progress but keeps your selected interface language.", cancel: "Cancel", resetEverything: "Reset everything",
  offlinePack: "Offline pack", noPaidApi: "No paid API · Progress stays in your browser", foundationCourses: "Complete learning paths", novaWelcome: "Meet Nova, your learning signal", featuresPath: "A path that unlocks", featuresHeart: "Learn with intention", featuresDaily: "Momentum daily", featuresReview: "Review smarter", moreRoadmap: "More lessons are planned in the roadmap.",
  basicUserInfo: "Basic user information", displayName: "Display name", displayNameQuestion: "What should NovaLang call you?", ageRange: "Age range", country: "Country/region", region: "City/prefecture", occupationStatus: "Occupation or student status", optional: "Optional", skipOptional: "Skip optional details",
  chooseNiches: "Choose your learning focus", primaryFocus: "Primary focus", dailyCommunication: "Daily Communication", examPreparation: "Exam Preparation", careerSpecialized: "Career / Specialized Fields", comingSoon: "Coming soon", changeNiche: "Change niche", changeGoalTrack: "Change goal/exam track", changeLevel: "Change level", nicheChangeQuestion: "You changed your learning focus. What would you like to do?", takePlacementTest: "Take a placement test", enterLevelManually: "Enter my level manually", startFromBeginning: "Start from the beginning", keepCurrentLevel: "Keep my current level",
  userInformation: "User Information", languageSettingsSection: "Language Settings", learningPreferences: "Learning Preferences", progressSection: "Progress", appSettings: "App Settings", legal: "Legal", account: "Account", termsOfService: "Terms of Service", privacyPolicy: "Privacy Policy", termsPlaceholder: "Terms of Service will be added later.", privacyPlaceholder: "Privacy Policy will be added later.", soundPronunciation: "Sound / pronunciation", enabled: "Enabled", resetLocalData: "Reset local data", completedLessons: "Completed lessons", mistakesSummary: "Mistakes summary",
  displayNamePlaceholder: "What should NovaLang call you?", agePlaceholder: "Optional", countryPlaceholder: "For example: Japan, Vietnam...", regionPlaceholder: "Optional", occupationPlaceholder: "For example: student, engineer, office worker...", providerLater: "This login provider will be connected later.", orUseEmail: "or use email", setupProgress: "Nova setup", placementChoiceTitle: "Do you want to take a placement test?", chooseLevelManually: "Choose level manually", dailyGoalReward: "You completed today's goal! +1 heart", resumeLesson: "Resume where you left off", next: "Next", questionsCount: "{count} questions", recommendedPath: "NovaLang recommends starting from: {level}",
  emailError: "Enter a valid email address.", passwordError: "Your password needs at least 6 characters.", nameError: "Enter a display name.", notFound: "This path is not on Nova’s map.", returnHome: "Return home", startWithBasics: "Start with the basics", basicsHelp: "Complete beginners practice letters and sounds first. Everyday greetings unlock after you finish or skip this step.", skipBasics: "Skip the basics"
};

export type TranslationKey = keyof typeof en;
const vi: Record<TranslationKey, string> = {
  appName: "NovaLang", tagline: "Làm chủ ngôn ngữ qua những hành trình học tập được hỗ trợ bởi AI.", signIn: "Đăng nhập", signOut: "Đăng xuất", startLearning: "Bắt đầu học", exploreCourses: "Khám phá khóa học",
  chooseNativeLanguage: "Chọn ngôn ngữ mẹ đẻ của bạn", nativeLanguageHelp: "Ngôn ngữ mẹ đẻ tách biệt với ngôn ngữ bạn đang học.", chooseLearningLanguage: "Chọn ngôn ngữ bạn muốn học", chooseLevel: "Bạn đang bắt đầu ở đâu?", chooseGoal: "Đặt mục tiêu hằng ngày", chooseDailyGoal: "Chọn mục tiêu hằng ngày", searchLanguage: "Tìm kiếm ngôn ngữ", popularLanguages: "Ngôn ngữ phổ biến", allLanguages: "Tất cả ngôn ngữ", selectedNativeLanguage: "Ngôn ngữ mẹ đẻ đã chọn", uiLanguage: "Ngôn ngữ giao diện", changeNativeLanguage: "Đổi ngôn ngữ mẹ đẻ", unsupportedUINotice: "Dùng giao diện tiếng Anh", englishFallbackNotice: "Ngôn ngữ mẹ đẻ của bạn đã được lưu. Hiện tại giao diện chưa hỗ trợ đầy đủ ngôn ngữ này, nên NovaLang sẽ dùng tiếng Anh cho giao diện.", save: "Lưu", placementTest: "Kiểm tra xếp lớp", startFromZero: "Bắt đầu từ số 0",
  english: "Tiếng Anh", vietnamese: "Tiếng Việt", japanese: "Tiếng Nhật", spanish: "Tiếng Tây Ban Nha", beginner: "Mới bắt đầu", elementary: "Sơ cấp", intermediate: "Trung cấp", casual: "Nhẹ nhàng", regular: "Đều đặn", serious: "Nghiêm túc", minutesDay: "phút/ngày",
  back: "Quay lại", backToCourse: "Quay lại lộ trình", reviewLesson: "Xem lại bài học", previousMicro: "Xem lại bước trước", nextMicroNav: "Tiếp theo", continue: "Tiếp tục", launchPath: "Bắt đầu lộ trình", welcomeBack: "Chào mừng trở lại", continueStreak: "Tiếp tục chuỗi học", email: "Email", password: "Mật khẩu", forgotPassword: "Quên mật khẩu?", enterApp: "Vào NovaLang", createProfile: "Tạo hồ sơ", continueExplorer: "Tiếp tục với tư cách người khám phá",
  home: "Trang chủ", learn: "Học", practice: "Luyện tập", review: "Ôn tập", mistakes: "Lỗi sai", flashcards: "Thẻ ghi nhớ", profile: "Hồ sơ", settings: "Cài đặt",
  totalXp: "Tổng XP", streak: "Chuỗi ngày", hearts: "Trái tim", lessonsComplete: "Bài đã hoàn thành", dailyGoal: "Mục tiêu hôm nay", xpToday: "XP kiếm được hôm nay", coursePath: "Lộ trình khóa học", currentLevel: "Cấp độ hiện tại", level: "Cấp độ", unit: "Chương", placed: "Đã xếp lớp", completed: "Hoàn thành", locked: "Đã khóa", current: "Hiện tại",
  signalLive: "Tín hiệu {language} của bạn đã sẵn sàng.", signalDescription: "Hoàn thành bài phát sáng; từng bài nhỏ sẽ mở khóa bước tiếp theo.", reviewChamber: "Phòng ôn tập", practiceDescription: "Ôn nội dung đã học để nhận XP và hồi một trái tim.", mistakeSignals: "Tín hiệu lỗi sai", reviewMistakes: "Ôn lỗi sai",
  lessonIntro: "Giới thiệu bài", canDo: "Mục tiêu có thể làm", microLessons: "Bài học nhỏ", microProgress: "Tiến độ bài học nhỏ", beginMicro: "Bắt đầu bài nhỏ", continueMicro: "Tiếp tục bài nhỏ", nextMicro: "Bài nhỏ tiếp theo", microComplete: "Hoàn thành bài nhỏ", lessonComplete: "Hoàn thành bài chính", questComplete: "Hoàn thành hành trình", xpEarned: "XP nhận được", accuracy: "Độ chính xác", correct: "Đúng", heartsLeft: "Trái tim còn lại", newQuestUnlocked: "Đã mở khóa bài mới", coursePathButton: "Lộ trình",
  readingLabel: "Cách đọc", exampleWordLabel: "Từ ví dụ", meaningLabel: "Nghĩa", exampleLabel: "Ví dụ", translationLabel: "Dịch", vocabulary: "Từ vựng", pronunciation: "Phát âm", grammar: "Ngữ pháp", dialogue: "Hội thoại", saveFlashcard: "Lưu thẻ", saved: "Đã lưu", explanation: "Giải thích", exercises: "Bài tập", startExercises: "Bắt đầu bài tập · {count}", exerciseNumber: "Bài tập {current}/{total}", checkAnswer: "Kiểm tra", nextExercise: "Câu tiếp theo", finishMicro: "Hoàn thành bài nhỏ", correctSignal: "Chính xác", notQuite: "Chưa đúng", practiceRecover: "Luyện tập để hồi trái tim",
  lockedLessonTitle: "Bài học này vẫn đang khóa", lockedLessonText: "Hãy hoàn thành bài trước và các bài học nhỏ của nó.", lockedMicroTitle: "Bài học nhỏ này đang khóa", lockedMicroText: "Hoàn thành bài nhỏ trước để tiếp tục.", loading: "Nova đang điều chỉnh tín hiệu học…", playPronunciation: "Nghe phát âm", speaking: "Đang phát...", speechNotSupported: "Trình duyệt này không hỗ trợ phát âm.", pronunciationFailed: "Không thể phát âm trên trình duyệt này.", voiceUnavailable: "Không tìm thấy giọng {language} phù hợp. Hãy thêm giọng này trong cài đặt trình duyệt hoặc thiết bị.",
  placementTitle: "Tìm điểm bắt đầu phù hợp", placementDescription: "Trả lời các câu hỏi tổng hợp. Nova sẽ đề xuất cấp độ theo CEFR hoặc kiểu JLPT.", startPlacement: "Bắt đầu kiểm tra xếp lớp", skipPlacement: "Bắt đầu từ số 0", placementQuestion: "Câu hỏi xếp lớp", placementResult: "Cấp độ được đề xuất", score: "Điểm", recommendedUnit: "Chương đề xuất", recommendedLesson: "Bài đề xuất", startRecommended: "Bắt đầu lộ trình đề xuất", retakePlacement: "Làm lại kiểm tra",
  dailyReview: "Ôn tập hằng ngày", weakWords: "Từ còn yếu", grammarReview: "Ôn ngữ pháp", pronunciationReview: "Ôn phát âm", mistakeReview: "Ôn lỗi sai", dueItems: "mục cần ôn", knewIt: "Tôi nhớ rồi", reviewAgain: "Ôn lại", reviewEmpty: "Hiện chưa có mục nào đến hạn ôn.", reviewEmptyHelp: "Hoàn thành bài học nhỏ để xây dựng lịch ôn cách quãng.",
  flashcardTitle: "Thẻ ghi nhớ đã lưu", flashcardHelp: "Chạm vào thẻ để lật.", flashcardEmpty: "Kho từ của bạn đang trống", mistakesTitle: "Biến tín hiệu yếu thành điểm mạnh.", noMistakes: "Không còn lỗi chưa xử lý", retrySignal: "Thử lại", improved: "Đã cải thiện!",
  profileTitle: "Hồ sơ người khám phá", achievementGrid: "Thành tích", languageSettings: "Cài đặt ngôn ngữ", nativeLanguage: "Ngôn ngữ bản địa", learningLanguage: "Ngôn ngữ đang học", changeNativeHelp: "Đổi ngôn ngữ giao diện không làm mất tiến độ.", changeLearningWarning: "Đổi ngôn ngữ học sẽ đổi khóa học hiển thị nhưng vẫn giữ tiến độ từng khóa.", resetProgress: "Đặt lại tiến độ", resetTitle: "Đặt lại tín hiệu học?", resetBody: "Thao tác này xóa tiến độ học nhưng giữ ngôn ngữ giao diện.", cancel: "Hủy", resetEverything: "Xóa toàn bộ tiến độ",
  offlinePack: "Gói ngoại tuyến", noPaidApi: "Không API trả phí · Tiến độ lưu trong trình duyệt", foundationCourses: "Lộ trình học hoàn chỉnh", novaWelcome: "Gặp Nova, tín hiệu học tập của bạn", featuresPath: "Lộ trình mở khóa", featuresHeart: "Học có chủ đích", featuresDaily: "Duy trì mỗi ngày", featuresReview: "Ôn tập thông minh", moreRoadmap: "Các bài mới nằm trong lộ trình phát triển.",
  basicUserInfo: "Thông tin cơ bản", displayName: "Tên hiển thị", displayNameQuestion: "Bạn muốn NovaLang gọi bạn là gì?", ageRange: "Độ tuổi", country: "Quốc gia/khu vực", region: "Thành phố/tỉnh", occupationStatus: "Nghề nghiệp hoặc tình trạng học tập", optional: "Không bắt buộc", skipOptional: "Bỏ qua thông tin không bắt buộc",
  chooseNiches: "Chọn trọng tâm học", primaryFocus: "Trọng tâm chính", dailyCommunication: "Giao tiếp hằng ngày", examPreparation: "Luyện thi", careerSpecialized: "Nghề nghiệp / Lĩnh vực chuyên môn", comingSoon: "Sắp ra mắt", changeNiche: "Đổi mục tiêu học", changeGoalTrack: "Đổi mục tiêu/lộ trình thi", changeLevel: "Đổi trình độ", nicheChangeQuestion: "Bạn đã đổi mục tiêu học. Bạn muốn bắt đầu như thế nào?", takePlacementTest: "Làm bài kiểm tra trình độ", enterLevelManually: "Nhập trình độ thủ công", startFromBeginning: "Bắt đầu lại từ đầu", keepCurrentLevel: "Giữ trình độ hiện tại",
  userInformation: "Thông tin người dùng", languageSettingsSection: "Cài đặt ngôn ngữ", learningPreferences: "Tùy chọn học", progressSection: "Tiến độ", appSettings: "Cài đặt ứng dụng", legal: "Pháp lý", account: "Tài khoản", termsOfService: "Điều khoản dịch vụ", privacyPolicy: "Chính sách quyền riêng tư", termsPlaceholder: "Điều khoản dịch vụ sẽ được thêm sau.", privacyPlaceholder: "Chính sách quyền riêng tư sẽ được thêm sau.", soundPronunciation: "Âm thanh / phát âm", enabled: "Đang bật", resetLocalData: "Đặt lại dữ liệu local", completedLessons: "Bài đã hoàn thành", mistakesSummary: "Tóm tắt lỗi sai",
  displayNamePlaceholder: "Bạn muốn NovaLang gọi bạn là gì?", agePlaceholder: "Không bắt buộc", countryPlaceholder: "Ví dụ: Nhật Bản, Việt Nam...", regionPlaceholder: "Không bắt buộc", occupationPlaceholder: "Ví dụ: sinh viên, kỹ sư, nhân viên văn phòng...", providerLater: "Tính năng đăng nhập này sẽ được kết nối sau.", orUseEmail: "hoặc dùng email", setupProgress: "Thiết lập Nova", placementChoiceTitle: "Bạn có muốn làm bài kiểm tra trình độ không?", chooseLevelManually: "Chọn trình độ thủ công", dailyGoalReward: "Bạn đã hoàn thành mục tiêu hôm nay! +1 tim", resumeLesson: "Tiếp tục từ chỗ đã dừng", next: "Tiếp theo", questionsCount: "{count} câu hỏi", recommendedPath: "NovaLang khuyến nghị bạn bắt đầu từ: {level}",
  emailError: "Hãy nhập địa chỉ email hợp lệ.", passwordError: "Mật khẩu cần ít nhất 6 ký tự.", nameError: "Hãy nhập tên hiển thị.", notFound: "Lối đi này không có trên bản đồ của Nova.", returnHome: "Về trang chủ", startWithBasics: "Bắt đầu với phần nền tảng", basicsHelp: "Người mới học luyện chữ cái và âm trước. Các bài chào hỏi hằng ngày sẽ mở sau khi bạn hoàn thành hoặc bỏ qua bước này.", skipBasics: "Bỏ qua phần nền tảng"
};

const ja: Record<TranslationKey, string> = {
  appName: "NovaLang", tagline: "AIクエストで言語をマスターしよう。", signIn: "ログイン", signOut: "ログアウト", startLearning: "学習を始める", exploreCourses: "コースを見る",
  chooseNativeLanguage: "母語を選択してください", nativeLanguageHelp: "母語と学習する言語は別々に保存されます。", chooseLearningLanguage: "学習したい言語を選択してください", chooseLevel: "現在のレベルは？", chooseGoal: "毎日の目標を設定", chooseDailyGoal: "毎日の目標を選択", searchLanguage: "言語を検索", popularLanguages: "人気の言語", allLanguages: "すべての言語", selectedNativeLanguage: "選択した母語", uiLanguage: "インターフェース言語", changeNativeLanguage: "母語を変更", unsupportedUINotice: "英語インターフェースにフォールバック", englishFallbackNotice: "母語が保存されました。この言語の完全なUI翻訳はまだ利用できないため、NovaLangは英語のインターフェースを使用します。", save: "保存", placementTest: "レベルチェック", startFromZero: "ゼロから始める",
  english: "英語", vietnamese: "ベトナム語", japanese: "日本語", spanish: "スペイン語", beginner: "初心者", elementary: "初級", intermediate: "中級", casual: "カジュアル", regular: "レギュラー", serious: "本格的", minutesDay: "分/日",
  back: "戻る", backToCourse: "コースに戻る", reviewLesson: "レッスンを見直す", previousMicro: "前のレッスン", nextMicroNav: "次のレッスン", continue: "続ける", launchPath: "コースを始める", welcomeBack: "おかえりなさい", continueStreak: "連続学習を続ける", email: "メール", password: "パスワード", forgotPassword: "パスワードを忘れた？", enterApp: "NovaLangへ", createProfile: "プロフィール作成", continueExplorer: "ゲストとして続ける",
  home: "ホーム", learn: "学習", practice: "練習", review: "復習", mistakes: "間違い", flashcards: "単語カード", profile: "プロフィール", settings: "設定",
  totalXp: "合計XP", streak: "連続日数", hearts: "ハート", lessonsComplete: "完了レッスン", dailyGoal: "今日の目標", xpToday: "今日のXP", coursePath: "コースパス", currentLevel: "現在のレベル", level: "レベル", unit: "ユニット", placed: "レベル判定済み", completed: "完了", locked: "ロック", current: "現在",
  signalLive: "{language}のシグナルが準備できました。", signalDescription: "光るレッスンとマイクロレッスンを順番に完了しましょう。", reviewChamber: "復習ルーム", practiceDescription: "学習済み内容を練習してXPとハートを回復。", mistakeSignals: "間違いシグナル", reviewMistakes: "間違いを復習",
  lessonIntro: "レッスン紹介", canDo: "できること", microLessons: "マイクロレッスン", microProgress: "マイクロ進捗", beginMicro: "始める", continueMicro: "続ける", nextMicro: "次のマイクロレッスン", microComplete: "マイクロレッスン完了", lessonComplete: "メインレッスン完了", questComplete: "クエスト完了", xpEarned: "獲得XP", accuracy: "正解率", correct: "正解", heartsLeft: "残りハート", newQuestUnlocked: "新しいレッスン解放", coursePathButton: "コースパス",
  readingLabel: "読み方", exampleWordLabel: "例の単語", meaningLabel: "意味", exampleLabel: "例文", translationLabel: "翻訳", vocabulary: "単語", pronunciation: "発音", grammar: "文法", dialogue: "会話", saveFlashcard: "カードを保存", saved: "保存済み", explanation: "説明", exercises: "練習問題", startExercises: "練習を始める · {count}", exerciseNumber: "練習 {current}/{total}", checkAnswer: "答えを確認", nextExercise: "次の問題", finishMicro: "マイクロレッスンを完了", correctSignal: "正解です", notQuite: "もう一度", practiceRecover: "練習してハートを回復",
  lockedLessonTitle: "このレッスンはロック中です", lockedLessonText: "前のレッスンとマイクロレッスンを完了してください。", lockedMicroTitle: "このマイクロレッスンはロック中です", lockedMicroText: "前のマイクロレッスンを完了してください。", loading: "学習シグナルを調整中…", playPronunciation: "発音を聞く", speaking: "再生中...", speechNotSupported: "このブラウザは音声再生に対応していません。", pronunciationFailed: "このブラウザでは発音を再生できません。", voiceUnavailable: "対応する{language}音声がありません。ブラウザまたは端末の音声設定に追加してください。",
  placementTitle: "最適な開始地点を見つけよう", placementDescription: "総合問題に答えると、NovaがCEFRまたはJLPT形式の開始レベルを判定します。", startPlacement: "レベルチェック開始", skipPlacement: "ゼロから始める", placementQuestion: "レベルチェック問題", placementResult: "おすすめレベル", score: "スコア", recommendedUnit: "おすすめユニット", recommendedLesson: "おすすめレッスン", startRecommended: "おすすめから開始", retakePlacement: "再テスト",
  dailyReview: "今日の復習", weakWords: "苦手な単語", grammarReview: "文法復習", pronunciationReview: "発音復習", mistakeReview: "間違い復習", dueItems: "件の復習", knewIt: "覚えていた", reviewAgain: "もう一度", reviewEmpty: "今は復習項目がありません。", reviewEmptyHelp: "マイクロレッスンを完了すると復習キューが作られます。",
  flashcardTitle: "保存した単語カード", flashcardHelp: "タップして裏返します。", flashcardEmpty: "単語ボックスは空です", mistakesTitle: "弱いシグナルを強みに変えよう。", noMistakes: "未解決の間違いはありません", retrySignal: "もう一度", improved: "改善しました！",
  profileTitle: "学習プロフィール", achievementGrid: "実績", languageSettings: "言語設定", nativeLanguage: "母語", learningLanguage: "学習言語", changeNativeHelp: "表示言語を変更しても学習進捗は保持されます。", changeLearningWarning: "学習言語を変更すると表示コースが変わりますが、進捗は保持されます。", resetProgress: "進捗をリセット", resetTitle: "学習シグナルをリセットしますか？", resetBody: "学習進捗を削除しますが、表示言語は保持します。", cancel: "キャンセル", resetEverything: "すべてリセット",
  offlinePack: "オフラインパック", noPaidApi: "有料APIなし · 進捗はブラウザに保存", foundationCourses: "完全学習パス", novaWelcome: "学習シグナルNova", featuresPath: "解放されるパス", featuresHeart: "集中して学ぶ", featuresDaily: "毎日の勢い", featuresReview: "スマート復習", moreRoadmap: "今後のレッスンはロードマップをご覧ください。",
  basicUserInfo: "基本情報", displayName: "表示名", displayNameQuestion: "NovaLangで何と呼びますか？", ageRange: "年齢層", country: "国・地域", region: "都市・都道府県", occupationStatus: "職業・学生ステータス", optional: "任意", skipOptional: "任意項目をスキップ",
  chooseNiches: "学習フォーカスを選択", primaryFocus: "主なフォーカス", dailyCommunication: "日常会話", examPreparation: "試験対策", careerSpecialized: "仕事・専門分野", comingSoon: "近日公開", changeNiche: "フォーカス変更", changeGoalTrack: "目標・試験ルート変更", changeLevel: "レベル変更", nicheChangeQuestion: "学習フォーカスを変更しました。どう始めますか？", takePlacementTest: "レベルチェックを受ける", enterLevelManually: "レベルを手動入力", startFromBeginning: "最初から始める", keepCurrentLevel: "現在のレベルを維持",
  userInformation: "ユーザー情報", languageSettingsSection: "言語設定", learningPreferences: "学習設定", progressSection: "進捗", appSettings: "アプリ設定", legal: "法務", account: "アカウント", termsOfService: "利用規約", privacyPolicy: "プライバシーポリシー", termsPlaceholder: "利用規約は後で追加されます。", privacyPlaceholder: "プライバシーポリシーは後で追加されます。", soundPronunciation: "音声・発音", enabled: "有効", resetLocalData: "ローカルデータをリセット", completedLessons: "完了レッスン", mistakesSummary: "間違いの概要",
  displayNamePlaceholder: "What should NovaLang call you?", agePlaceholder: "Optional", countryPlaceholder: "For example: Japan, Vietnam...", regionPlaceholder: "Optional", occupationPlaceholder: "For example: student, engineer, office worker...", providerLater: "This login provider will be connected later.", orUseEmail: "or use email", setupProgress: "Nova setup", placementChoiceTitle: "Do you want to take a placement test?", chooseLevelManually: "Choose level manually", dailyGoalReward: "You completed today's goal! +1 heart", resumeLesson: "Resume where you left off", next: "Next", questionsCount: "{count} questions", recommendedPath: "NovaLang recommends starting from: {level}",
  emailError: "有効なメールアドレスを入力してください。", passwordError: "パスワードは6文字以上必要です。", nameError: "表示名を入力してください。", notFound: "この道はNovaのマップにありません。", returnHome: "ホームへ", startWithBasics: "基礎から始めましょう", basicsHelp: "初心者はまず文字と音を練習します。日常のあいさつは、この段階を終えるかスキップすると開放されます。", skipBasics: "基礎をスキップ"
};

const es: Record<TranslationKey, string> = {
  appName: "NovaLang", tagline: "Domina idiomas mediante misiones de aprendizaje.", signIn: "Iniciar sesión", signOut: "Cerrar sesión", startLearning: "Empezar a aprender", exploreCourses: "Explorar cursos",
  chooseNativeLanguage: "Elige tu idioma nativo", nativeLanguageHelp: "Tu idioma nativo es independiente del idioma que estudias.", chooseLearningLanguage: "Elige el idioma que quieres aprender", chooseLevel: "¿Desde qué nivel empiezas?", chooseGoal: "Define tu objetivo diario", chooseDailyGoal: "Elige tu objetivo diario", searchLanguage: "Buscar idiomas", popularLanguages: "Idiomas populares", allLanguages: "Todos los idiomas", selectedNativeLanguage: "Idioma nativo seleccionado", uiLanguage: "Idioma de la interfaz", changeNativeLanguage: "Cambiar idioma nativo", unsupportedUINotice: "Interfaz alternativa en inglés", englishFallbackNotice: "Tu idioma nativo ha sido guardado. La traducción completa de la interfaz aún no está disponible, por lo que NovaLang usará inglés para la interfaz.", save: "Guardar", placementTest: "Prueba de nivel", startFromZero: "Empezar desde cero",
  english: "Inglés", vietnamese: "Vietnamita", japanese: "Japonés", spanish: "Español", beginner: "Principiante", elementary: "Elemental", intermediate: "Intermedio", casual: "Tranquilo", regular: "Regular", serious: "Intensivo", minutesDay: "min/día",
  back: "Atrás", backToCourse: "Volver al curso", reviewLesson: "Revisar la lección", previousMicro: "Lección anterior", nextMicroNav: "Siguiente lección", continue: "Continuar", launchPath: "Iniciar mi ruta", welcomeBack: "Bienvenido de nuevo", continueStreak: "Continúa tu racha", email: "Correo electrónico", password: "Contraseña", forgotPassword: "¿Olvidaste tu contraseña?", enterApp: "Entrar en NovaLang", createProfile: "Crear un perfil", continueExplorer: "Continuar como explorador",
  home: "Inicio", learn: "Aprender", practice: "Practicar", review: "Repasar", mistakes: "Errores", flashcards: "Tarjetas", profile: "Perfil", settings: "Ajustes",
  totalXp: "XP total", streak: "Racha diaria", hearts: "Corazones", lessonsComplete: "Lecciones completadas", dailyGoal: "Objetivo diario", xpToday: "XP ganado hoy", coursePath: "Ruta del curso", currentLevel: "Nivel actual", level: "Nivel", unit: "Unidad", placed: "Clasificado", completed: "Completado", locked: "Bloqueado", current: "Actual",
  signalLive: "Tu señal de {language} está activa.", signalDescription: "Completa cada lección y sus microlecciones para desbloquear el siguiente paso.", reviewChamber: "Sala de repaso", practiceDescription: "Practica contenidos aprendidos para ganar XP y recuperar un corazón.", mistakeSignals: "Señales de error", reviewMistakes: "Repasar errores",
  lessonIntro: "Introducción de la lección", canDo: "Objetivo práctico", microLessons: "Microlecciones", microProgress: "Progreso de microlecciones", beginMicro: "Empezar microlección", continueMicro: "Continuar microlección", nextMicro: "Siguiente microlección", microComplete: "Microlección completada", lessonComplete: "Lección principal completada", questComplete: "Misión completada", xpEarned: "XP ganado", accuracy: "Precisión", correct: "Correcto", heartsLeft: "Corazones restantes", newQuestUnlocked: "Nueva misión desbloqueada", coursePathButton: "Ruta del curso",
  readingLabel: "Lectura", exampleWordLabel: "Palabra de ejemplo", meaningLabel: "Significado", exampleLabel: "Ejemplo", translationLabel: "Traducción", vocabulary: "Vocabulario", pronunciation: "Pronunciación", grammar: "Gramática", dialogue: "Diálogo", saveFlashcard: "Guardar tarjeta", saved: "Guardado", explanation: "Explicación", exercises: "Ejercicios", startExercises: "Empezar ejercicios · {count}", exerciseNumber: "Ejercicio {current}/{total}", checkAnswer: "Comprobar respuesta", nextExercise: "Siguiente ejercicio", finishMicro: "Terminar microlección", correctSignal: "Respuesta correcta", notQuite: "Todavía no", practiceRecover: "Practica para recuperar corazones",
  lockedLessonTitle: "Esta lección sigue bloqueada", lockedLessonText: "Completa primero la lección anterior y sus microlecciones.", lockedMicroTitle: "Esta microlección está bloqueada", lockedMicroText: "Completa la microlección anterior para continuar.", loading: "Ajustando la señal de aprendizaje…", playPronunciation: "Escuchar pronunciación", speaking: "Reproduciendo...", speechNotSupported: "Este navegador no admite la reproducción de voz.", pronunciationFailed: "La pronunciación no está disponible en este navegador.", voiceUnavailable: "No hay una voz {language} compatible instalada. Añádela en los ajustes de voz del navegador o dispositivo.",
  placementTitle: "Encuentra tu mejor punto de partida", placementDescription: "Responde preguntas mixtas. Nova recomendará un nivel inicial CEFR o de estilo JLPT.", startPlacement: "Iniciar prueba de nivel", skipPlacement: "Empezar desde cero", placementQuestion: "Pregunta de nivel", placementResult: "Tu nivel recomendado", score: "Puntuación", recommendedUnit: "Unidad recomendada", recommendedLesson: "Lección recomendada", startRecommended: "Empezar la ruta recomendada", retakePlacement: "Repetir prueba de nivel",
  dailyReview: "Repaso diario", weakWords: "Palabras débiles", grammarReview: "Repaso de gramática", pronunciationReview: "Repaso de pronunciación", mistakeReview: "Repaso de errores", dueItems: "elementos pendientes", knewIt: "Lo sabía", reviewAgain: "Repasar otra vez", reviewEmpty: "Todavía no hay elementos pendientes.", reviewEmptyHelp: "Completa microlecciones para crear tu cola de repaso espaciado.",
  flashcardTitle: "Tus tarjetas guardadas", flashcardHelp: "Toca una tarjeta para voltearla.", flashcardEmpty: "Tu archivo de palabras está vacío", mistakesTitle: "Convierte las señales débiles en fortalezas.", noMistakes: "No hay errores sin resolver", retrySignal: "Reintentar", improved: "¡Mejorado!",
  profileTitle: "Perfil del explorador", achievementGrid: "Logros", languageSettings: "Ajustes de idioma", nativeLanguage: "Idioma nativo", learningLanguage: "Idioma de aprendizaje", changeNativeHelp: "Cambiar el idioma de la interfaz conserva todo tu progreso.", changeLearningWarning: "Cambiar el idioma de aprendizaje cambia el curso visible, pero conserva el progreso de cada curso.", resetProgress: "Restablecer progreso", resetTitle: "¿Restablecer tu señal de aprendizaje?", resetBody: "Esto elimina el progreso de aprendizaje, pero conserva el idioma de la interfaz.", cancel: "Cancelar", resetEverything: "Restablecer todo",
  offlinePack: "Paquete sin conexión", noPaidApi: "Sin API de pago · El progreso permanece en tu navegador", foundationCourses: "Rutas completas de aprendizaje", novaWelcome: "Conoce a Nova, tu señal de aprendizaje", featuresPath: "Una ruta que se desbloquea", featuresHeart: "Aprende con intención", featuresDaily: "Impulso diario", featuresReview: "Repasa mejor", moreRoadmap: "Hay más lecciones previstas en la hoja de ruta.",
  basicUserInfo: "Información básica", displayName: "Nombre visible", displayNameQuestion: "¿Cómo debería llamarte NovaLang?", ageRange: "Rango de edad", country: "País/región", region: "Ciudad/provincia", occupationStatus: "Ocupación o estado de estudiante", optional: "Opcional", skipOptional: "Omitir datos opcionales",
  chooseNiches: "Elige tu enfoque de aprendizaje", primaryFocus: "Enfoque principal", dailyCommunication: "Comunicación diaria", examPreparation: "Preparación de exámenes", careerSpecialized: "Carrera / campos especializados", comingSoon: "Próximamente", changeNiche: "Cambiar enfoque", changeGoalTrack: "Cambiar objetivo/ruta de examen", changeLevel: "Cambiar nivel", nicheChangeQuestion: "Cambiaste tu enfoque de aprendizaje. ¿Cómo quieres empezar?", takePlacementTest: "Hacer una prueba de nivel", enterLevelManually: "Introducir mi nivel manualmente", startFromBeginning: "Empezar desde el principio", keepCurrentLevel: "Mantener mi nivel actual",
  userInformation: "Información de usuario", languageSettingsSection: "Ajustes de idioma", learningPreferences: "Preferencias de aprendizaje", progressSection: "Progreso", appSettings: "Ajustes de la app", legal: "Legal", account: "Cuenta", termsOfService: "Términos de servicio", privacyPolicy: "Política de privacidad", termsPlaceholder: "Los Términos de servicio se añadirán más tarde.", privacyPlaceholder: "La Política de privacidad se añadirá más tarde.", soundPronunciation: "Sonido / pronunciación", enabled: "Activado", resetLocalData: "Restablecer datos locales", completedLessons: "Lecciones completadas", mistakesSummary: "Resumen de errores",
  displayNamePlaceholder: "What should NovaLang call you?", agePlaceholder: "Optional", countryPlaceholder: "For example: Japan, Vietnam...", regionPlaceholder: "Optional", occupationPlaceholder: "For example: student, engineer, office worker...", providerLater: "This login provider will be connected later.", orUseEmail: "or use email", setupProgress: "Nova setup", placementChoiceTitle: "Do you want to take a placement test?", chooseLevelManually: "Choose level manually", dailyGoalReward: "You completed today's goal! +1 heart", resumeLesson: "Resume where you left off", next: "Next", questionsCount: "{count} questions", recommendedPath: "NovaLang recommends starting from: {level}",
  emailError: "Introduce un correo electrónico válido.", passwordError: "La contraseña debe tener al menos 6 caracteres.", nameError: "Introduce un nombre visible.", notFound: "Esta ruta no está en el mapa de Nova.", returnHome: "Volver al inicio", startWithBasics: "Empieza con lo básico", basicsHelp: "Los principiantes practican primero letras y sonidos. Los saludos cotidianos se desbloquean al terminar u omitir este paso.", skipBasics: "Omitir lo básico"
};

export const translations: Record<SupportedUILanguage, Record<TranslationKey, string>> = { en, vi, ja, es };
export const supportedUILanguages: SupportedUILanguage[] = ["en", "vi", "ja", "es"];
export const isNativeLanguageUISupported = (code: string): code is SupportedUILanguage => supportedUILanguages.includes(code as SupportedUILanguage);
export const isUISupportedForNativeLanguage = isNativeLanguageUISupported;
export const getEffectiveUILanguage = (nativeLanguageCode: string): SupportedUILanguage => isNativeLanguageUISupported(nativeLanguageCode) ? nativeLanguageCode : "en";



